default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

queue: &queue
  <<: *default
  migrations_paths: db/queue_migrations

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrations

development:
  primary:
    <<: *default
    database: hyperbulletin_development
  queue:
    <<: *queue
    database: hyperbulletin_development_queue
  cache:
    <<: *cache
    database: hyperbulletin_development_cache

test:
  primary:
    <<: *default
    database: hyperbulletin_test
  queue:
    <<: *queue
    database: hyperbulletin_test_queue
  cache:
    <<: *cache
    database: hyperbulletin_test_cache

production:
  primary:
    <<: *default
    database: hyperbulletin_production
    username: hyperbulletin
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *queue
    database: hyperbulletin_production_queue
    url: <%= ENV['QUEUE_DATABASE_URL'] %>
  cache:
    <<: *cache
    database: hyperbulletin_production_cache
    url: <%= ENV['CACHE_DATABASE_URL'] %>
